<?php
require_once __DIR__ . '/includes/php/bootstrap.php';
$pageSlug = jr_page_slug();
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>JR MARKETING (PVT) LTD — Sales Report</title>
    <link rel="icon" href="data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'><rect width='32' height='32' rx='6' fill='%230a5c2e'/><text x='50%25' y='55%25' font-size='13' font-weight='900' fill='white' text-anchor='middle' dominant-baseline='middle' font-family='Arial'>JR</text></svg>">
    <link rel="stylesheet" href="assets/css/variables.css"><link rel="stylesheet" href="assets/css/base.css">
    <style>
        *,*::before,*::after{box-sizing:border-box;margin:0;padding:0}body{font-family:'Segoe UI',Arial,sans-serif;background:#eef1f8;min-height:100vh;display:flex;flex-direction:column}.navbar{background:#0a5c2e;height:52px;display:flex;align-items:center;justify-content:space-between;padding:0 18px 0 0;position:sticky;top:0;z-index:200;box-shadow:0 2px 10px rgba(10,92,46,0.4);flex-shrink:0}.navbar-left{display:flex;align-items:center;height:100%}.nav-sidebar-toggle{width:52px;height:52px;display:flex;align-items:center;justify-content:center;cursor:pointer;color:rgba(255,255,255,0.8)}.navbar-brand{display:flex;align-items:center;gap:8px;color:#fff;font-weight:800;font-size:15px;padding:0 14px 0 8px;white-space:nowrap}.brand-dot{width:9px;height:9px;border-radius:50%;background:#22c55e}.navbar-right{display:flex;align-items:center;gap:5px}.nav-pos-btn{display:flex;align-items:center;gap:6px;background:rgba(255,255,255,0.12);border:1px solid rgba(255,255,255,0.2);border-radius:8px;color:white;padding:0 12px;height:34px;font-size:13px;font-weight:700;cursor:pointer}.nav-divider{width:1px;height:22px;background:rgba(255,255,255,0.2);margin:0 4px}.nav-date{color:rgba(255,255,255,0.85);font-size:13px;font-weight:600;white-space:nowrap}.nav-icon-btn{width:36px;height:36px;border-radius:8px;background:transparent;border:none;color:rgba(255,255,255,0.75);cursor:pointer;display:flex;align-items:center;justify-content:center}.nav-user{display:flex;align-items:center;gap:7px;background:rgba(255,255,255,0.1);border:1px solid rgba(255,255,255,0.18);border-radius:8px;padding:0 10px;height:34px;color:white;font-size:13px;font-weight:600;cursor:pointer}.nav-user-avatar{width:24px;height:24px;border-radius:50%;background:#16a34a;display:flex;align-items:center;justify-content:center;font-size:11px;font-weight:800}
        .layout{display:flex;flex:1;min-height:calc(100vh - 52px)}.sidebar{width:240px;background:#f8f9fc;border-right:1px solid #dde3f0;flex-shrink:0;overflow-y:auto;transition:width .28s ease}.sidebar.collapsed{width:0}.sidebar-inner{padding:6px 0 28px}.sidebar-menu{list-style:none}.menu-item{position:relative}.menu-link{display:flex;align-items:center;justify-content:space-between;padding:10px 16px 10px 14px;color:#374151;font-size:13.5px;font-weight:500;text-decoration:none;cursor:pointer;border-left:3px solid transparent;white-space:nowrap}.menu-link:hover{background:#dcfce7;color:#15803d}.menu-link.active{background:#dcfce7;color:#15803d;border-left-color:#16a34a;font-weight:700}.menu-link-left{display:flex;align-items:center;gap:10px}.menu-icon{width:20px;height:20px;display:flex;align-items:center;justify-content:center;flex-shrink:0;color:#6b7280}.menu-link.active .menu-icon,.menu-link:hover .menu-icon{color:#16a34a}.menu-chevron{font-size:10px;color:#9ca3af;transition:transform .2s}.menu-item.open>.menu-link .menu-chevron{transform:rotate(90deg)}.submenu{display:none;background:#f0fdf4;list-style:none}.menu-item.open .submenu{display:block}.submenu-link{display:flex;align-items:center;gap:8px;padding:8px 16px 8px 40px;color:#4b5563;font-size:12.5px;text-decoration:none;white-space:nowrap}.submenu-link:hover{color:#15803d;background:#bbf7d0}.submenu-link.active{color:#15803d;background:#bbf7d0;font-weight:600}
        .main{flex:1;overflow-y:auto;display:flex;flex-direction:column}.content-header{background:#0a5c2e;padding:22px 26px 20px;flex-shrink:0}.page-title{font-size:22px;font-weight:800;color:#fff;display:flex;align-items:center;gap:10px}.content-body{padding:20px;background:#eef1f8;flex:1}
        .card{background:#fff;border-radius:12px;box-shadow:0 1px 5px rgba(0,0,0,.07);padding:20px;margin-bottom:18px}
        .toolbar{display:flex;align-items:center;gap:10px;flex-wrap:wrap;margin-bottom:14px}.toolbar input,.toolbar select{height:36px;border:1px solid #d1d5db;border-radius:8px;padding:0 10px;font-size:13px;outline:none}
        .btn{height:36px;padding:0 16px;border:none;border-radius:8px;font-size:13px;font-weight:600;cursor:pointer;display:inline-flex;align-items:center;gap:6px}.btn-primary{background:#16a34a;color:#fff}.btn-outline{background:#fff;color:#374151;border:1px solid #d1d5db}
        .stats-row{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin-bottom:18px}.stat-card{background:#fff;border-radius:12px;padding:18px;box-shadow:0 1px 5px rgba(0,0,0,.07);text-align:center}.stat-label{font-size:12px;color:#6b7280}.stat-value{font-size:24px;font-weight:800;margin-top:4px;color:#111827}
        table{width:100%;border-collapse:collapse}th{background:#f9fafb;padding:10px 12px;font-size:12px;font-weight:600;color:#6b7280;text-align:left;text-transform:uppercase;border-bottom:2px solid #e5e7eb}td{padding:10px 12px;font-size:13px;color:#374151;border-bottom:1px solid #f3f4f6}tr:hover{background:#f0fdf4}.empty-state{text-align:center;padding:40px;color:#9ca3af;font-size:14px}
        @media(max-width:1100px){.stats-row{grid-template-columns:repeat(2,1fr)}}@media(max-width:768px){.sidebar{display:none}.sidebar.mobile-open{display:flex;position:fixed;left:0;top:52px;height:calc(100vh - 52px);z-index:300;width:240px;box-shadow:4px 0 20px rgba(0,0,0,.2)}.stats-row{grid-template-columns:1fr 1fr}.nav-date{display:none}}
    </style>
</head>
<body>
    <nav class="navbar"><div class="navbar-left"><div class="nav-sidebar-toggle" id="sidebar-toggle"><svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" viewBox="0 0 24 24"><line x1="3" y1="6" x2="21" y2="6"/><line x1="3" y1="12" x2="21" y2="12"/><line x1="3" y1="18" x2="21" y2="18"/></svg></div><div class="navbar-brand">JR MARKETING (PVT) LTD <span class="brand-dot"></span></div></div><div class="navbar-right"><button class="nav-pos-btn" onclick="location.href='pos.php'"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="none" stroke="currentColor" stroke-width="2.2" viewBox="0 0 24 24"><rect x="2" y="3" width="20" height="14" rx="2"/><line x1="8" y1="21" x2="16" y2="21"/><line x1="12" y1="17" x2="12" y2="21"/></svg> POS</button><div class="nav-divider"></div><span class="nav-date" id="nav-date"></span><div class="nav-divider"></div><button class="nav-icon-btn" title="Notifications"><svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path d="M18 8A6 6 0 0 0 6 8c0 7-3 9-3 9h18s-3-2-3-9"/><path d="M13.73 21a2 2 0 0 1-3.46 0"/></svg></button><div class="nav-user" id="nav-user"><div class="nav-user-avatar" id="nav-avatar">A</div><span id="nav-username">Admin</span></div></div></nav>
    <div class="layout">
        <aside class="sidebar" id="sidebar"><div class="sidebar-inner"><ul class="sidebar-menu">
            <li class="menu-item"><a href="dashboard.php" class="menu-link"><span class="menu-link-left"><span class="menu-icon"><svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/><polyline points="9 22 9 12 15 12 15 22"/></svg></span>Home</span></a></li>
            <li class="menu-item" data-menu="contacts"><div class="menu-link" onclick="toggleMenu('contacts')"><span class="menu-link-left"><span class="menu-icon"><svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/></svg></span>Contacts</span><span class="menu-chevron">&#9654;</span></div><ul class="submenu"><li><a class="submenu-link" href="customers.php">&#8227;&nbsp; Customers</a></li><li><a class="submenu-link" href="suppliers.php">&#8227;&nbsp; Suppliers</a></li></ul></li>
            <li class="menu-item" data-menu="products"><div class="menu-link" onclick="toggleMenu('products')"><span class="menu-link-left"><span class="menu-icon"><svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z"/></svg></span>Products</span><span class="menu-chevron">&#9654;</span></div><ul class="submenu"><li><a class="submenu-link" href="products.php">&#8227;&nbsp; Products List</a></li><li><a class="submenu-link" href="products.php#add">&#8227;&nbsp; Add New Product</a></li><li><a class="submenu-link" href="units.php">&#8227;&nbsp; Units</a></li><li><a class="submenu-link" href="stock.php">&#8227;&nbsp; Stock</a></li></ul></li>
            <li class="menu-item" data-menu="purchases"><div class="menu-link" onclick="toggleMenu('purchases')"><span class="menu-link-left"><span class="menu-icon"><svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><polyline points="8 17 12 21 16 17"/><line x1="12" y1="12" x2="12" y2="21"/></svg></span>Purchases</span><span class="menu-chevron">&#9654;</span></div><ul class="submenu"><li><a class="submenu-link" href="purchases.php">&#8227;&nbsp; Purchase List</a></li><li><a class="submenu-link" href="purchases.php#add">&#8227;&nbsp; Add Purchase</a></li><li><a class="submenu-link" href="purchases.php#return">&#8227;&nbsp; Purchase Return</a></li></ul></li>
            <li class="menu-item" data-menu="sell"><div class="menu-link" onclick="toggleMenu('sell')"><span class="menu-link-left"><span class="menu-icon"><svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><polyline points="17 1 21 5 17 9"/><path d="M3 11V9a4 4 0 0 1 4-4h14"/></svg></span>Sell</span><span class="menu-chevron">&#9654;</span></div><ul class="submenu"><li><a class="submenu-link" href="sales.php">&#8227;&nbsp; All Sales</a></li><li><a class="submenu-link" href="add-sale.php">&#8227;&nbsp; Add Sale</a></li><li><a class="submenu-link" href="sale-return.php">&#8227;&nbsp; Sale Return</a></li><li><a class="submenu-link" href="sales.php#quotations">&#8227;&nbsp; Quotations</a></li><li><a class="submenu-link" href="sales.php#credit">&#8227;&nbsp; Credit Sales</a></li><li><a class="submenu-link" href="sales.php#cheques">&#8227;&nbsp; Cheques</a></li></ul></li>
            <li class="menu-item" data-menu="expenses"><div class="menu-link" onclick="toggleMenu('expenses')"><span class="menu-link-left"><span class="menu-icon"><svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><rect x="1" y="4" width="22" height="16" rx="2" ry="2"/><line x1="1" y1="10" x2="23" y2="10"/></svg></span>Expenses</span><span class="menu-chevron">&#9654;</span></div><ul class="submenu"><li><a class="submenu-link" href="expenses.php">&#8227;&nbsp; Expense List</a></li><li><a class="submenu-link" href="expenses.php#add">&#8227;&nbsp; Add Expense</a></li><li><a class="submenu-link" href="expense-categories.php">&#8227;&nbsp; Expense Categories</a></li></ul></li>
            <li class="menu-item"><a href="payments.php" class="menu-link"><span class="menu-link-left"><span class="menu-icon"><svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><rect x="1" y="4" width="22" height="16" rx="2"/><line x1="1" y1="10" x2="23" y2="10"/></svg></span>Payments</span></a></li>
            <li class="menu-item open" data-menu="reports"><div class="menu-link active" onclick="toggleMenu('reports')"><span class="menu-link-left"><span class="menu-icon"><svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><line x1="18" y1="20" x2="18" y2="10"/><line x1="12" y1="20" x2="12" y2="4"/><line x1="6" y1="20" x2="6" y2="14"/></svg></span>Reports</span><span class="menu-chevron">&#9654;</span></div><ul class="submenu"><li><a class="submenu-link" href="profit-loss.php">&#8227;&nbsp; Profit / Loss</a></li><li><a class="submenu-link" href="purchase-report.php">&#8227;&nbsp; Purchase Report</a></li><li><a class="submenu-link active" href="sales-report.php">&#8227;&nbsp; Sales Report</a></li><li><a class="submenu-link" href="expense-report.php">&#8227;&nbsp; Expense Report</a></li><li><a class="submenu-link" href="stock-report.php">&#8227;&nbsp; Stock Report</a></li><li><a class="submenu-link" href="tax-report.php">&#8227;&nbsp; Tax Report</a></li></ul></li>
        </ul></div></aside>
        <main class="main">
            <div class="content-header"><div class="page-title">🛒 Sales Report</div></div>
            <div class="content-body">
                <div class="toolbar"><label style="font-size:13px;font-weight:600">From</label><input type="date" id="date-from" onchange="gen()"><label style="font-size:13px;font-weight:600">To</label><input type="date" id="date-to" onchange="gen()"><button class="btn btn-primary" onclick="gen()">Generate</button><button class="btn btn-outline" onclick="window.print()">🖨 Print</button><button class="btn btn-outline" onclick="exportCSV()">📥 Export</button></div>
                <div class="stats-row">
                    <div class="stat-card"><div class="stat-label">Total Sales</div><div class="stat-value" id="s-count">0</div></div>
                    <div class="stat-card"><div class="stat-label">Revenue</div><div class="stat-value" id="s-total" style="color:#16a34a">LKR 0</div></div>
                    <div class="stat-card"><div class="stat-label">Avg. Sale</div><div class="stat-value" id="s-avg">LKR 0</div></div>
                    <div class="stat-card"><div class="stat-label">Items Sold</div><div class="stat-value" id="s-items">0</div></div>
                </div>
                <div class="card">
                    <table><thead><tr><th>#</th><th>Date</th><th>Invoice</th><th>Customer</th><th>Method</th><th>Items</th><th>Total</th><th>Status</th></tr></thead><tbody id="report-tbody"></tbody></table>
                    <div class="empty-state" id="empty">No sales data for selected period.</div>
                    <div style="margin-top:12px;padding-top:10px;border-top:2px solid #e5e7eb;text-align:right;font-size:15px;font-weight:700" id="grand-total"></div>
                </div>
            </div>
        </main>
    </div>
    <script src="assets/js/utils.js"></script><script src="assets/js/auth.js"></script><script src="assets/js/toast.js"></script>
    <script>
    document.addEventListener('DOMContentLoaded',()=>{Auth.requireAuth();const s=Auth.getSession();if(s&&s.user){document.getElementById('nav-username').textContent=s.user.name||s.user.username;document.getElementById('nav-avatar').textContent=(s.user.name||s.user.username).charAt(0).toUpperCase();}document.getElementById('nav-date').textContent=new Date().toLocaleDateString('en-GB');document.getElementById('sidebar-toggle').addEventListener('click',()=>{const sb=document.getElementById('sidebar');if(window.innerWidth<=768)sb.classList.toggle('mobile-open');else sb.classList.toggle('collapsed');});document.getElementById('nav-user').addEventListener('click',()=>{if(confirm('Logout?'))Auth.logout();});const n=new Date();document.getElementById('date-from').value=new Date(n.getFullYear(),n.getMonth(),1).toISOString().split('T')[0];document.getElementById('date-to').value=n.toISOString().split('T')[0];gen();});
    function toggleMenu(id){const i=document.querySelector(`[data-menu="${id}"]`);if(!i)return;const w=i.classList.contains('open');document.querySelectorAll('.menu-item.open').forEach(e=>e.classList.remove('open'));if(!w)i.classList.add('open');}
    function fmtC(v){return 'LKR '+parseFloat(v||0).toLocaleString('en-LK',{minimumFractionDigits:2});}
    function gen(){
        const f=document.getElementById('date-from').value,t=document.getElementById('date-to').value;
        const all=JSON.parse(localStorage.getItem('jr_sales')||'[]').filter(s=>(!f||s.date>=f)&&(!t||s.date<=t));
        const total=all.reduce((s,x)=>s+parseFloat(x.total||0),0);
        const totalItems=all.reduce((s,x)=>s+(x.items||[]).reduce((a,it)=>a+(it.qty||0),0),0);
        document.getElementById('s-count').textContent=all.length;
        document.getElementById('s-total').textContent=fmtC(total);
        document.getElementById('s-avg').textContent=fmtC(all.length?total/all.length:0);
        document.getElementById('s-items').textContent=totalItems;
        const tb=document.getElementById('report-tbody'),em=document.getElementById('empty');
        if(!all.length){tb.innerHTML='';em.style.display='';document.getElementById('grand-total').innerHTML='';return;}
        em.style.display='none';
        tb.innerHTML=all.map((s,i)=>{const badge=s.status==='completed'?'background:#dcfce7;color:#16a34a':'background:#fef9c3;color:#ca8a04';return`<tr><td>${i+1}</td><td>${s.date}</td><td style="font-family:monospace">${s.invoice||s.id}</td><td>${s.customer||'Walk-in'}</td><td>${s.method||'Cash'}</td><td>${(s.items||[]).length}</td><td style="font-weight:600">${fmtC(s.total)}</td><td><span style="${badge};padding:2px 10px;border-radius:20px;font-size:11px;font-weight:600">${s.status||'—'}</span></td></tr>`;}).join('');
        document.getElementById('grand-total').innerHTML='Grand Total: '+fmtC(total);
    }
    function exportCSV(){const all=JSON.parse(localStorage.getItem('jr_sales')||'[]');if(!all.length){Toast.warning('No data');return;}const c='Date,Invoice,Customer,Method,Items,Total,Status\n'+all.map(s=>`"${s.date}","${s.invoice||s.id}","${s.customer||'Walk-in'}","${s.method||'Cash'}",${(s.items||[]).length},${s.total},"${s.status||''}"`).join('\n');const b=new Blob([c],{type:'text/csv'});const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='sales-report.csv';a.click();}
    </script>
</body>
</html>
