<?php
require_once __DIR__ . '/includes/php/bootstrap.php';
$pageSlug = jr_page_slug();
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>JR MARKETING (PVT) LTD — Suppliers</title>
    <link rel="icon" href="data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'><rect width='32' height='32' rx='6' fill='%230a5c2e'/><text x='50%25' y='55%25' font-size='13' font-weight='900' fill='white' text-anchor='middle' dominant-baseline='middle' font-family='Arial'>JR</text></svg>">
    <link rel="stylesheet" href="assets/css/variables.css">
    <link rel="stylesheet" href="assets/css/base.css">
    <style>
        *,*::before,*::after{box-sizing:border-box;margin:0;padding:0}body{font-family:'Segoe UI',Arial,sans-serif;background:#eef1f8;min-height:100vh;display:flex;flex-direction:column}.navbar{background:#0a5c2e;height:52px;display:flex;align-items:center;justify-content:space-between;padding:0 18px 0 0;position:sticky;top:0;z-index:200;box-shadow:0 2px 10px rgba(10,92,46,0.4);flex-shrink:0}.navbar-left{display:flex;align-items:center;height:100%}.nav-sidebar-toggle{width:52px;height:52px;display:flex;align-items:center;justify-content:center;cursor:pointer;color:rgba(255,255,255,0.8);transition:background .2s;flex-shrink:0}.nav-sidebar-toggle:hover{background:rgba(255,255,255,0.1)}.navbar-brand{display:flex;align-items:center;gap:8px;color:#fff;font-weight:800;font-size:15px;letter-spacing:.5px;padding:0 14px 0 8px;white-space:nowrap}.brand-dot{width:9px;height:9px;border-radius:50%;background:#22c55e;display:inline-block;flex-shrink:0;margin-left:2px}.navbar-right{display:flex;align-items:center;gap:5px}.nav-pos-btn{display:flex;align-items:center;gap:6px;background:rgba(255,255,255,0.12);border:1px solid rgba(255,255,255,0.2);border-radius:8px;color:white;padding:0 12px;height:34px;font-size:13px;font-weight:700;cursor:pointer;letter-spacing:.5px;transition:background .2s}.nav-pos-btn:hover{background:rgba(255,255,255,0.22)}.nav-divider{width:1px;height:22px;background:rgba(255,255,255,0.2);margin:0 4px}.nav-date{color:rgba(255,255,255,0.85);font-size:13px;font-weight:600;padding:0 4px;white-space:nowrap}.nav-icon-btn{width:36px;height:36px;border-radius:8px;background:transparent;border:none;color:rgba(255,255,255,0.75);cursor:pointer;display:flex;align-items:center;justify-content:center;font-size:16px;transition:background .2s,color .2s}.nav-icon-btn:hover{background:rgba(255,255,255,0.12);color:white}.nav-user{display:flex;align-items:center;gap:7px;background:rgba(255,255,255,0.1);border:1px solid rgba(255,255,255,0.18);border-radius:8px;padding:0 10px;height:34px;color:white;font-size:13px;font-weight:600;cursor:pointer;transition:background .2s}.nav-user:hover{background:rgba(255,255,255,0.2)}.nav-user-avatar{width:24px;height:24px;border-radius:50%;background:#16a34a;display:flex;align-items:center;justify-content:center;font-size:11px;font-weight:800}
        .layout{display:flex;flex:1;min-height:calc(100vh - 52px)}.sidebar{width:240px;background:#f8f9fc;border-right:1px solid #dde3f0;flex-shrink:0;overflow-y:auto;overflow-x:hidden;transition:width .28s ease}.sidebar.collapsed{width:0}.sidebar-inner{padding:6px 0 28px}.sidebar-menu{list-style:none}.menu-item{position:relative}.menu-link{display:flex;align-items:center;justify-content:space-between;padding:10px 16px 10px 14px;color:#374151;font-size:13.5px;font-weight:500;text-decoration:none;cursor:pointer;transition:background .15s,color .15s;border-left:3px solid transparent;user-select:none;white-space:nowrap}.menu-link:hover{background:#dcfce7;color:#15803d;text-decoration:none}.menu-link.active{background:#dcfce7;color:#15803d;border-left-color:#16a34a;font-weight:700}.menu-link-left{display:flex;align-items:center;gap:10px}.menu-icon{width:20px;height:20px;display:flex;align-items:center;justify-content:center;flex-shrink:0;color:#6b7280}.menu-link.active .menu-icon,.menu-link:hover .menu-icon{color:#16a34a}.menu-chevron{font-size:10px;color:#9ca3af;transition:transform .2s;flex-shrink:0}.menu-item.open>.menu-link .menu-chevron{transform:rotate(90deg)}.submenu{display:none;background:#f0fdf4;list-style:none}.menu-item.open .submenu{display:block}.submenu-link{display:flex;align-items:center;gap:8px;padding:8px 16px 8px 40px;color:#4b5563;font-size:12.5px;text-decoration:none;transition:color .15s,background .15s;cursor:pointer;white-space:nowrap}.submenu-link:hover{color:#15803d;background:#bbf7d0;text-decoration:none}.submenu-link.active{color:#15803d;background:#bbf7d0;font-weight:600}
        .main{flex:1;overflow-y:auto;display:flex;flex-direction:column}.content-header{background:#0a5c2e;padding:22px 26px 20px;display:flex;align-items:center;justify-content:space-between;flex-shrink:0}.page-title{font-size:22px;font-weight:800;color:#fff;display:flex;align-items:center;gap:10px}.content-body{padding:20px;background:#eef1f8;flex:1}
        .card{background:#fff;border-radius:12px;box-shadow:0 1px 5px rgba(0,0,0,.07);padding:20px;margin-bottom:18px}.card-title{font-size:15px;font-weight:700;color:#111827;margin-bottom:16px}.toolbar{display:flex;align-items:center;gap:10px;flex-wrap:wrap;margin-bottom:14px}.toolbar input{height:36px;border:1px solid #d1d5db;border-radius:8px;padding:0 10px;font-size:13px;outline:none}.toolbar input:focus{border-color:#16a34a;box-shadow:0 0 0 3px rgba(22,163,74,.12)}.btn{height:36px;padding:0 16px;border:none;border-radius:8px;font-size:13px;font-weight:600;cursor:pointer;display:inline-flex;align-items:center;gap:6px;transition:background .2s}.btn-primary{background:#16a34a;color:#fff}.btn-primary:hover{background:#15803d}.btn-outline{background:#fff;color:#374151;border:1px solid #d1d5db}.btn-outline:hover{background:#f3f4f6}
        table{width:100%;border-collapse:collapse}th{background:#f9fafb;padding:10px 12px;font-size:12px;font-weight:600;color:#6b7280;text-align:left;text-transform:uppercase;letter-spacing:.5px;border-bottom:2px solid #e5e7eb}td{padding:10px 12px;font-size:13px;color:#374151;border-bottom:1px solid #f3f4f6}tr:hover{background:#f0fdf4}.empty-state{text-align:center;padding:40px;color:#9ca3af;font-size:14px}
        .form-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.form-group{display:flex;flex-direction:column;gap:4px}.form-group.full{grid-column:1/-1}.form-group label{font-size:12px;font-weight:600;color:#374151}.form-group input,.form-group select,.form-group textarea{height:38px;border:1px solid #d1d5db;border-radius:8px;padding:0 10px;font-size:13px;outline:none}.form-group input:focus,.form-group select:focus,.form-group textarea:focus{border-color:#16a34a;box-shadow:0 0 0 3px rgba(22,163,74,.12)}.form-group textarea{height:70px;padding:8px 10px;resize:vertical}.form-actions{display:flex;gap:10px;margin-top:16px;justify-content:flex-end}
        .tabs{display:flex;gap:0;border-bottom:2px solid #e5e7eb;margin-bottom:18px}.tab{padding:10px 20px;font-size:13px;font-weight:600;color:#6b7280;cursor:pointer;border-bottom:2px solid transparent;margin-bottom:-2px;transition:all .2s}.tab:hover{color:#15803d}.tab.active{color:#16a34a;border-bottom-color:#16a34a}.tab-content{display:none}.tab-content.active{display:block}
        .action-btn{width:30px;height:30px;border:none;border-radius:6px;background:#fee2e2;color:#ef4444;cursor:pointer;display:inline-flex;align-items:center;justify-content:center;transition:background .2s}.action-btn:hover{background:#fecaca}
        @media(max-width:768px){.sidebar{display:none}.sidebar.mobile-open{display:flex;position:fixed;left:0;top:52px;height:calc(100vh - 52px);z-index:300;width:240px;box-shadow:4px 0 20px rgba(0,0,0,.2)}.form-grid{grid-template-columns:1fr}.nav-date{display:none}}
    </style>
</head>
<body>
    <nav class="navbar"><div class="navbar-left"><div class="nav-sidebar-toggle" id="sidebar-toggle"><svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" viewBox="0 0 24 24"><line x1="3" y1="6" x2="21" y2="6"/><line x1="3" y1="12" x2="21" y2="12"/><line x1="3" y1="18" x2="21" y2="18"/></svg></div><div class="navbar-brand">JR MARKETING (PVT) LTD <span class="brand-dot"></span></div></div><div class="navbar-right"><button class="nav-pos-btn" onclick="location.href='pos.php'"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="none" stroke="currentColor" stroke-width="2.2" viewBox="0 0 24 24"><rect x="2" y="3" width="20" height="14" rx="2"/><line x1="8" y1="21" x2="16" y2="21"/><line x1="12" y1="17" x2="12" y2="21"/></svg> POS</button><div class="nav-divider"></div><span class="nav-date" id="nav-date"></span><div class="nav-divider"></div><button class="nav-icon-btn" title="Notifications"><svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path d="M18 8A6 6 0 0 0 6 8c0 7-3 9-3 9h18s-3-2-3-9"/><path d="M13.73 21a2 2 0 0 1-3.46 0"/></svg></button><div class="nav-user" id="nav-user"><div class="nav-user-avatar" id="nav-avatar">A</div><span id="nav-username">Admin</span></div></div></nav>

    <div class="layout">
        <aside class="sidebar" id="sidebar"><div class="sidebar-inner"><ul class="sidebar-menu">
            <li class="menu-item"><a href="dashboard.php" class="menu-link"><span class="menu-link-left"><span class="menu-icon"><svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/><polyline points="9 22 9 12 15 12 15 22"/></svg></span>Home</span></a></li>
            <li class="menu-item open" data-menu="contacts"><div class="menu-link active" onclick="toggleMenu('contacts')"><span class="menu-link-left"><span class="menu-icon"><svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M23 21v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75"/></svg></span>Contacts</span><span class="menu-chevron">&#9654;</span></div><ul class="submenu"><li><a class="submenu-link" href="customers.php">&#8227;&nbsp; Customers</a></li><li><a class="submenu-link active" href="suppliers.php">&#8227;&nbsp; Suppliers</a></li></ul></li>
            <li class="menu-item" data-menu="products"><div class="menu-link" onclick="toggleMenu('products')"><span class="menu-link-left"><span class="menu-icon"><svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z"/><polyline points="3.27 6.96 12 12.01 20.73 6.96"/><line x1="12" y1="22.08" x2="12" y2="12"/></svg></span>Products</span><span class="menu-chevron">&#9654;</span></div><ul class="submenu"><li><a class="submenu-link" href="products.php">&#8227;&nbsp; Products List</a></li><li><a class="submenu-link" href="products.php#add">&#8227;&nbsp; Add New Product</a></li><li><a class="submenu-link" href="units.php">&#8227;&nbsp; Units</a></li><li><a class="submenu-link" href="stock.php">&#8227;&nbsp; Stock</a></li></ul></li>
            <li class="menu-item" data-menu="purchases"><div class="menu-link" onclick="toggleMenu('purchases')"><span class="menu-link-left"><span class="menu-icon"><svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><polyline points="8 17 12 21 16 17"/><line x1="12" y1="12" x2="12" y2="21"/><path d="M20.88 18.09A5 5 0 0 0 18 9h-1.26A8 8 0 1 0 3 16.29"/></svg></span>Purchases</span><span class="menu-chevron">&#9654;</span></div><ul class="submenu"><li><a class="submenu-link" href="purchases.php">&#8227;&nbsp; Purchase List</a></li><li><a class="submenu-link" href="purchases.php#add">&#8227;&nbsp; Add Purchase</a></li><li><a class="submenu-link" href="purchases.php#return">&#8227;&nbsp; Purchase Return</a></li></ul></li>
            <li class="menu-item" data-menu="sell"><div class="menu-link" onclick="toggleMenu('sell')"><span class="menu-link-left"><span class="menu-icon"><svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><polyline points="17 1 21 5 17 9"/><path d="M3 11V9a4 4 0 0 1 4-4h14"/><polyline points="7 23 3 19 7 15"/><path d="M21 13v2a4 4 0 0 1-4 4H3"/></svg></span>Sell</span><span class="menu-chevron">&#9654;</span></div><ul class="submenu"><li><a class="submenu-link" href="sales.php">&#8227;&nbsp; All Sales</a></li><li><a class="submenu-link" href="add-sale.php">&#8227;&nbsp; Add Sale</a></li><li><a class="submenu-link" href="sale-return.php">&#8227;&nbsp; Sale Return</a></li><li><a class="submenu-link" href="sales.php#quotations">&#8227;&nbsp; Quotations</a></li><li><a class="submenu-link" href="sales.php#credit">&#8227;&nbsp; Credit Sales</a></li><li><a class="submenu-link" href="sales.php#cheques">&#8227;&nbsp; Cheques</a></li></ul></li>
            <li class="menu-item" data-menu="expenses"><div class="menu-link" onclick="toggleMenu('expenses')"><span class="menu-link-left"><span class="menu-icon"><svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><rect x="1" y="4" width="22" height="16" rx="2" ry="2"/><line x1="1" y1="10" x2="23" y2="10"/></svg></span>Expenses</span><span class="menu-chevron">&#9654;</span></div><ul class="submenu"><li><a class="submenu-link" href="expenses.php">&#8227;&nbsp; Expense List</a></li><li><a class="submenu-link" href="expenses.php#add">&#8227;&nbsp; Add Expense</a></li><li><a class="submenu-link" href="expense-categories.php">&#8227;&nbsp; Expense Categories</a></li></ul></li>
            <li class="menu-item"><a href="payments.php" class="menu-link"><span class="menu-link-left"><span class="menu-icon"><svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><rect x="1" y="4" width="22" height="16" rx="2"/><line x1="1" y1="10" x2="23" y2="10"/><line x1="7" y1="15" x2="10" y2="15"/><line x1="13" y1="15" x2="17" y2="15"/></svg></span>Payments</span></a></li>
            <li class="menu-item" data-menu="reports"><div class="menu-link" onclick="toggleMenu('reports')"><span class="menu-link-left"><span class="menu-icon"><svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><line x1="18" y1="20" x2="18" y2="10"/><line x1="12" y1="20" x2="12" y2="4"/><line x1="6" y1="20" x2="6" y2="14"/></svg></span>Reports</span><span class="menu-chevron">&#9654;</span></div><ul class="submenu"><li><a class="submenu-link" href="profit-loss.php">&#8227;&nbsp; Profit / Loss</a></li><li><a class="submenu-link" href="purchase-report.php">&#8227;&nbsp; Purchase Report</a></li><li><a class="submenu-link" href="sales-report.php">&#8227;&nbsp; Sales Report</a></li><li><a class="submenu-link" href="expense-report.php">&#8227;&nbsp; Expense Report</a></li><li><a class="submenu-link" href="stock-report.php">&#8227;&nbsp; Stock Report</a></li><li><a class="submenu-link" href="tax-report.php">&#8227;&nbsp; Tax Report</a></li></ul></li>
        </ul></div></aside>

        <main class="main">
            <div class="content-header"><div class="page-title"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"/><circle cx="12" cy="7" r="4"/></svg> Suppliers</div></div>
            <div class="content-body">
                <div class="tabs"><div class="tab active" onclick="switchTab('list')">Supplier List</div><div class="tab" onclick="switchTab('add')">+ Add Supplier</div></div>
                <div class="tab-content active" id="tab-list">
                    <div class="card">
                        <div class="toolbar"><input type="text" id="search-input" placeholder="Search suppliers..." style="flex:1;min-width:200px" oninput="renderList()"><button class="btn btn-primary" onclick="Importer.showModal('suppliers')" style="background:linear-gradient(135deg,#2563eb,#3b82f6)">📤 Import Data</button><button class="btn btn-outline" onclick="exportCSV()">📥 Export CSV</button></div>
                        <table><thead><tr><th>#</th><th>Company</th><th>Total Amount</th><th>Total Paid</th><th>Total Due</th><th>Date</th><th>Action</th></tr></thead><tbody id="supplier-tbody"></tbody></table>
                        <div class="empty-state" id="empty-state">No suppliers found. Add your first supplier!</div>
                    </div>
                </div>
                <div class="tab-content" id="tab-add">
                    <div class="card">
                        <div class="card-title">Supplier Information</div>
                        <div class="form-grid">
                            <div class="form-group"><label>Company Name *</label><input type="text" id="f-company" placeholder="Company name"></div>
                            <div class="form-group"><label>Supplier Contact ID</label><input type="text" id="f-contact-id" placeholder="Auto-generated" readonly style="background:#f9fafb;color:#9ca3af"></div>
                            <div class="form-group"><label>Contact Person</label><input type="text" id="f-contact" placeholder="Contact person name"></div>
                            <div class="form-group"><label>Phone *</label><input type="text" id="f-phone" placeholder="07X XXXX XXX"></div>
                            <div class="form-group"><label>Email</label><input type="email" id="f-email" placeholder="email@example.com"></div>
                        </div>
                        <div class="form-actions"><button class="btn btn-outline" onclick="resetForm()">Clear</button><button class="btn btn-primary" onclick="saveSupplier()">💾 Save Supplier</button></div>
                    </div>
                </div>
            </div>
        </main>
    </div>

    <script src="assets/js/utils.js"></script><script src="assets/js/auth.js"></script><script src="assets/js/toast.js"></script><script src="assets/js/importer.js"></script>
    <script>
    window._importRefresh = () => { renderList(); };
    document.addEventListener('DOMContentLoaded', () => {
        Auth.requireAuth();
        const session = Auth.getSession(); if (session && session.user) { document.getElementById('nav-username').textContent = session.user.name || session.user.username; document.getElementById('nav-avatar').textContent = (session.user.name || session.user.username).charAt(0).toUpperCase(); }
        document.getElementById('nav-date').textContent = new Date().toLocaleDateString('en-GB');
        document.getElementById('sidebar-toggle').addEventListener('click', () => { const sb = document.getElementById('sidebar'); if (window.innerWidth <= 768) sb.classList.toggle('mobile-open'); else sb.classList.toggle('collapsed'); });
        document.getElementById('nav-user').addEventListener('click', () => { if (confirm('Logout?')) Auth.logout(); });
        document.getElementById('f-contact-id').value = genSupContactId();
        if (location.hash === '#add') switchTab('add');
        renderList();
    });
    function toggleMenu(id) { const item = document.querySelector(`[data-menu="${id}"]`); if (!item) return; const w = item.classList.contains('open'); document.querySelectorAll('.menu-item.open').forEach(el => el.classList.remove('open')); if (!w) item.classList.add('open'); }
    function switchTab(name) { document.querySelectorAll('.tab').forEach((t,i) => t.classList.toggle('active', name==='list'?i===0:i===1)); document.getElementById('tab-list').classList.toggle('active', name==='list'); document.getElementById('tab-add').classList.toggle('active', name==='add'); }
    function getAll() { return JSON.parse(localStorage.getItem('jr_suppliers') || '[]'); }
    function saveAll(arr) { localStorage.setItem('jr_suppliers', JSON.stringify(arr)); }
    function genSupContactId() { return 'SC-' + String(Date.now()).slice(-6); }
    function saveSupplier() {
        const company = document.getElementById('f-company').value.trim();
        const phone = document.getElementById('f-phone').value.trim();
        if (!company || !phone) { Toast.error('Company Name and Phone are required.'); return; }
        const record = { id:'SUP-'+Date.now(), contactId: document.getElementById('f-contact-id').value || genSupContactId(), company, contact:document.getElementById('f-contact').value.trim(), phone, email:document.getElementById('f-email').value.trim(), createdAt:new Date().toISOString() };
        const all = getAll(); all.unshift(record); saveAll(all);
        Toast.success(`Supplier "${company}" saved!`); resetForm(); switchTab('list'); renderList();
    }
    function resetForm() { ['f-company','f-contact','f-phone','f-email'].forEach(id => document.getElementById(id).value = ''); document.getElementById('f-contact-id').value = genSupContactId(); }
    function renderList() {
        const q = (document.getElementById('search-input').value || '').toLowerCase();
        const all = getAll();
        const items = q ? all.filter(s => s.company.toLowerCase().includes(q) || s.phone.includes(q) || (s.contact||'').toLowerCase().includes(q)) : all;
        const tbody = document.getElementById('supplier-tbody'); const empty = document.getElementById('empty-state');
        if (!items.length) { tbody.innerHTML = ''; empty.style.display = ''; return; }
        empty.style.display = 'none';
        tbody.innerHTML = items.map((s,i) => {
            const totalAmt = parseFloat(s.totalPurchaseAmount||0) + parseFloat(s.balance||0);
            const totalPaid = parseFloat(s.totalPaid||0);
            const totalDue = parseFloat(s.totalPurchaseDue||0) + parseFloat(s.balance||0) - parseFloat(s.totalPaid||0);
            return `<tr><td>${i+1}</td><td><strong>${s.company}</strong></td><td><strong>LKR ${totalAmt.toLocaleString('en-LK',{minimumFractionDigits:2})}</strong></td><td><strong style="color:#166534">LKR ${totalPaid.toLocaleString('en-LK',{minimumFractionDigits:2})}</strong></td><td><strong style="color:${totalDue>0?'#dc2626':'#166534'}">LKR ${totalDue.toLocaleString('en-LK',{minimumFractionDigits:2})}</strong></td><td style="font-size:12px;color:#6b7280">${new Date(s.createdAt).toLocaleDateString('en-GB')}</td><td><button class="action-btn" onclick="deleteSupplier('${s.id}')"><svg width="15" height="15" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><polyline points="3 6 5 6 21 6"/><path d="M19 6l-1 14a2 2 0 0 1-2 2H8a2 2 0 0 1-2-2L5 6"/><path d="M10 11v6M14 11v6"/><path d="M9 6V4h6v2"/></svg></button></td></tr>`;
        }).join('');
    }
    function deleteSupplier(id) { if (!confirm('Delete this supplier?')) return; saveAll(getAll().filter(s => s.id !== id)); Toast.success('Supplier deleted.'); renderList(); }
    function exportCSV() { const all = getAll(); if (!all.length) { Toast.warning('No data.'); return; } const csv = 'Contact ID,Company,Contact,Phone,Email,Total Amount,Total Paid,Total Due,Added\n'+all.map(s=>{ const totalAmt=parseFloat(s.totalPurchaseAmount||0)+parseFloat(s.balance||0); const totalPaid=parseFloat(s.totalPaid||0); const totalDue=parseFloat(s.totalPurchaseDue||0)+parseFloat(s.balance||0)-parseFloat(s.totalPaid||0); return `"${s.contactId||''}","${s.company}","${s.contact||''}","${s.phone}","${s.email||''}",${totalAmt},${totalPaid},${totalDue},"${s.createdAt}"`; }).join('\n'); const b = new Blob([csv],{type:'text/csv'}); const a = document.createElement('a'); a.href = URL.createObjectURL(b); a.download='suppliers.csv'; a.click(); }
    </script>
</body>
</html>
